eporner:
   home: https://www.eporner.com
   savePath: D:\eporner\
   category:
      UHD: https://www.eporner.com/category/4k-porn/
   thread: 40   
      
proxy:
   host: 127.0.0.1
   port: 1080     
   
spring:
   data:
      mongodb:
         uri: mongodb://127.0.0.1:27017/file