eporner:
  home: https://www.eporner.com
  savePath: E:\eporner\
  category:
    UHD: https://www.eporner.com/category/4k-porn/
  thread: 50
  enableProxy: true

javfinder:
  home: https://javfinder.la
  savePath: D:\javfinder
  category:
    Uncensored: https://javfinder.la/category/uncensored/page-@{page}.html
    Hot: https://javfinder.la/category/@{category}/hot/page-@{page}.html
  categoryTemplate: https://javfinder.la/category/@{category}/page-@{page}.html
  thread: 100
  ignoreCode: FC2,XXX-AV,Heydouga,Tokyo Hot,Pacopacomama,H0930,C0930,H4610,10Musume
  enableProxy: true

pixiv:
  home: https://www.pixiv.net
  savePath: C:\pixiv
  templatePage: https://www.pixiv.net/artworks/@{id}
  newApi: https://www.pixiv.net/ajax/illust/new?limit=50&lastId=@{lastId}&type=@{type}&r18=true&lang=zh
  todayRank:
    normal:
    R-18: https://www.pixiv.net/ranking.php?mode=daily_r18&content=illust&p=@{page}&format=json&date=@{date}
  cookie: __cfduid=da8eb863b88589f6f64690223193305371616855351; first_visit_datetime_pc=2021-03-27+23%3A29%3A12; p_ab_id=4; p_ab_id_2=9; p_ab_d_id=1793816877; yuid_b=EFSEcXY; __utmz=235335808.1616855357.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); PHPSESSID=33820661_T3GnnSbRhhKpGr1wUu1KhZ7PAq9qwCoy; device_token=ac5106a406d35108593602c0609b12bd; c_type=25; a_type=0; b_type=1; _ga=GA1.2.384117637.1616855357; login_ever=yes; __utmv=235335808.|2=login%20ever=yes=1^3=plan=normal=1^5=gender=male=1^6=user_id=33820661=1^9=p_ab_id=4=1^10=p_ab_id_2=9=1^11=lang=zh=1; privacy_policy_agreement=2; tag_view_ranking=0xsDLqCEW6~zIv0cf5VVk~tTvZK72fmv~MM6RXH_rlN~4vG5vwS-Ns~vCeZ80ZP0O~tIthLEM_gP~LEmyJ-RN72~-IrOV3901X~O0WKFZuVbs~-oGijJmC5S~b1z7OfgtVC~zyKU3Q5L4C~3FPpuwlQDR~dve3nXgd1M~kGYw4gQ11Z~20WHHnlmIc~lH5YZxnbfC; __utma=235335808.384117637.1616855357.1616855357.1616943856.2; __utmc=235335808; __cf_bm=22ea73a076cc9e4e62ae33b898e266f49db19611-1616943858-1800-ARBtwUW8Sva/wJRFH8KAWMrbkHil7BE99OdvmlfyY8xizQtPJjE9x8oDs9Svlq+mjBrrdX/evEfLFODixLKTG8Dwe39lTPwnpOGThKYfk7PiHGYiP9ZtgfPGSjsQ6WOMAnlsRBdmm/PLlBeoa6YDZ5m/5OJoqpNCXnkfrY3N0FoBUOn4wujIpP/vvun6H6tkyA==; __utmt=1; __utmb=235335808.1.10.1616943856
  thread: 30
  enableProxy: true

hanime:
  home: https://hanime.tv/
  savePath: D:\hanime
  imageApi: https://hr.hanime.tv/api/v8/community_uploads?channel_name__in[]=@{channel}&query_method=seek&before_id=@{beforeId}&loc=https://hanime.tv
  thread: 24
  videoListApi: https://search.hanime.tv
  videoDownloadApi: https://members.hanime.tv/api/v1/downloads/@{slug}
  auth: ad170b14e4c91572f9ab09709fae0754
  auth_expires: 1557134607
  enableProxy: true

wallhaven:
  home: https://wallhaven.cc
  savePath: G:\wallhaven
  imageApi: https://wallhaven.cc/search?q=&categories=@{categories}&purity=@{purity}&atleast=@{atleast}&sorting=date_added&order=desc&page=@{page}
  categories:
    - general
    - anime
    - people
  purity:
    - SFW
    - sketchy
    - NSFW
  cookie: __cfduid=d7de3bd7c0b7f35648d7ca4b45d092d0a1556795980; _pk_ses.1.01b8=1; remember_web_59ba36addc2b2f9401580f014c7f58ea4e30989d=eyJpdiI6IitTTVRFNFBmZVFtQ0ZZMit0M1JEWlE9PSIsInZhbHVlIjoiQmtqZXNRTlphbTlOMmlhUFJRSDhqaW5RNW9zMGhkWDVFQnd6YzRxYlNDbEM5Sys5bFhadlE1SllSOGZrb281TGFrTkxtaEFLaGtuUkY1azBueXlRS2JtT1k5cWtxVU5tbzJNMmlOOWRIalwvVmM3cE5Pd3BDd0JkSHlneEYrTVhTNWhtUER6Y1FXcmxiMUxcL2hjTk9cL05sSDJJZmJQQzhYRU1uRU5JQjZvQ25NOWRnaHBVeWp6XC9leXBEa3B2aVhpYyIsIm1hYyI6Ijg0ZTg3OTcwYTE4OWRlOWE4MjUyODMyNTIxYjU2NTBmMWM3NWM4Njc0MjE4YTU3M2I5NGE0NTI3YTg5Yzc2MDkifQ%3D%3D; _pk_id.1.01b8=893fa051d6a2880e.1559142259.2.1559144190.1559144132.; XSRF-TOKEN=eyJpdiI6IlFFNm4xNzRUUHB0ZjRTSG56NDlObXc9PSIsInZhbHVlIjoiN0dkSGN1YTdGN3FzM3dLRnJ6UFBrUkpSNXNiOEpTRWVzT3pTTUlTNkpQMXQ2YkNsbjRReFRxdlc1bWNrR0phSSIsIm1hYyI6ImU4MDFmOWNjMjNkMjllYmY2MGQ4MTNiYWFiMDZiNGFmZDE0MWZjMTg0MTUyMjc1YzNiZDM4N2NhMDBjYTMxNmMifQ%3D%3D; wallhaven_session=eyJpdiI6InNXRzZGYzhPRlh0SzQ3Z2hMd0dmWkE9PSIsInZhbHVlIjoiUUlxR3hMNnlmWm5FUlpEQjE4WDFmWXdYTmRjVXhGNGZ5bDM0anRSTUpOWU1pTEtPZkpwcnZVU1ZcL2ZyQnVjTlEiLCJtYWMiOiIzY2Y4MTlhMDQ1MjczMWU3ZGI4Y2E1ZjM2YzIxNTJhY2MwZjZjMzE3MzgxN2ExOTc1OGE1NzcwOWQzNDEzN2Q1In0%3D
  enableProxy: true

javhihi:
  home: https://www1.javhihi.com/
  #home: https://www1.javbuz.com/
  #home: https://xart.letfap.com/
  movie: ${javhihi.home}movie?sort=published&page=@{page}&ajax=1
  savePath: E:\javhihi\
  #savePath: D:\javbuz\
  #savePath: D:\xart.letfap\
  thread: 20
  enableProxy: true

pornhub:
  home: https://www.pornhub.com
  savePath: E:\pornhub\
  searchUrl: https://www.pornhub.com/video/search?search=@{key}&hd=1&page=@{page}&p=professional&min_duration=10
  channels: https://pornhub.com/channels/@{channelName}/videos?o=da&page=@{page}
  categories:
    - hentai
  categoriesUrl: https://www.pornhub.com/categories/@{categories}
  categoriesUrlByNum: https://pornhub.com/video?c=@{categories}&hd=1&page=@{page}&min_duration=10&p=professional
  incategoriesUrl: https://pornhub.com/video/incategories/@{categories}/@{incategories}?p=professional&min_duration=10&hd=1&page=@{page}&t=a
  thread: 30
  enableProxy: true

youtubeSpider:
  home: https://www.findyoutube.net/
  api: https://www.findyoutube.net/result
  savePath: F:\youtube\
  thread: 5
  enableProxy: true
  googleApi:
    #key: AIzaSyA7H9oVSXwPbOyIaC2kKV1UTtoOyjRjgmw
    key: AIzaSyBSLTrFguRE5p75BJ6OzhwXuiPHTTO8Ryc
    playlists: https://www.googleapis.com/youtube/v3/playlists?part=snippet&channelId=@{channelId}&key=${youtube.googleApi.key}&maxResults=50
    playlistItems: https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=@{playlistId}&key=${youtube.googleApi.key}&maxResults=50
    search: https://www.googleapis.com/youtube/v3/search?key=${youtube.googleApi.key}&part=snippet&channelId=@{channelId}&maxResults=50&type=video

by114:
  home: https://www.by114.pw/
  template: https://www.by114.pw/forum-@{type}-@{page}.html
  savePath: C:\by114\
  enableProxy: true

javbangers:
  home: https://www.javbangers.com/
  template: https://www.javbangers.com/categories/@{categories}/?mode=async&function=get_block&block_id=list_videos_common_videos_list&sort_by=post_date&from=@{page}&_=@{time}
  savePath: E:\javbangers\
  cookie: PHPSESSID=7c50fe5e3162b0947fd7501670927d08; kt_ips=18.163.190.129; kt_member=6db553ff0a261deeadd9cce6ba9e8cb4; kt_tcookie=1; kt_is_visited=1
  enableProxy: true
  thread: 30

kissjav:
  home: https://kissjav.com
  savePath: C:\kissjav\
  template: https://kissjav.com/videos/@{category}/@{page}/
  cookie: Angie_89d7248ae8=edc15da8d21e3985fa7c2ec67b549b9d
  thread: 30
  enableProxy: true

javbus:
  home: https://www.javbus.com
  enableProxy: true
  thread: 100
  actressesListTemplate: ${javbus.home}/@{category}/actresses/@{page}
  actressesDetailsTemplate: ${javbus.home}/@{category}/star/@{name}
  uncensoredPage: https://www.javbus.com/uncensored/page/@{page}
  avTemplate: ${javbus.home}/@{code}
  magnetApi: https://www.javbus.com/ajax/uncledatoolsbyajax.php?gid=@{gid}&lang=zh&uc=1
  savePath: E:\javbus\

javrave:
  home: https://javrave.club/
  template: https://javrave.club/cat/@{category}/page/@{page}/
  savePath: E:\javrave\
  enableProxy: true
  thread: 30
  api: https://javideo.pw/api/source/@{key}

javfull:
  home: https://javfull.net/
  template: https://javfull.net/@{category}/page/@{page}/
  savePath: C:\javfull\
  enableProxy: true
  thread: 30
  api: https://www.fembed.com/api/source/@{key}

javhuge:
  home: http://javhuge.com/
  template: http://javhuge.com/vod/show/class/@{category}/id/22/page/@{page}
  savePath: E:\javhuge\
  thread: 30
  enableProxy: true

hqporner:
  home: https://hqporner.com
  template: ${hqporner.home}/category/@{category}/@{page}
  enableProxy: true
  thread: 30
  savePath: E:\hqporner\

netflav:
  home: https://netflav.com/
  listTemplate: https://netflav.com/@{category}?page=@{page}
  videoTemplate: https://netflav.com/video?id=@{videoId}
  videoInfoApi: https://netflav.com/api98/video/v2/retrieveVideo/@{videoId}
  fileApiTemplate: https://www.avple.video/api/source/@{key}
  enableProxy: true
  thread: 30
  savePath: E:\netflav\

video:
  minWidth: 640
  minHeight: 640