eporner:
  home: https://www.eporner.com
  savePath: E:\eporner\
  category:
    UHD: https://www.eporner.com/category/4k-porn/
  thread: 50
  enableProxy: true

javfinder:
  home: https://javfinder.la
  savePath: D:\javfinder
  category:
    Uncensored: https://javfinder.la/category/uncensored/page-@{page}.html
    Hot: https://javfinder.la/category/@{category}/hot/page-@{page}.html
  categoryTemplate: https://javfinder.la/category/@{category}/page-@{page}.html
  thread: 100
  ignoreCode: FC2,XXX-AV,Heydouga,Tokyo Hot,Pacopacomama,H0930,C0930,H4610,10Musume
  enableProxy: true

pixiv:
  home: https://www.pixiv.net
  savePath: E:\pixiv
  todayRank:
    normal:
    R-18: https://www.pixiv.net/ranking.php?mode=daily_r18&content=illust&p=@{page}&format=json&date=@{date}
  cookie: first_visit_datetime_pc=2019-03-29+10%3A36%3A01; p_ab_id=6; p_ab_id_2=5; p_ab_d_id=1564507400; __utmc=235335808; _ga=GA1.2.1000168084.1553823364; _gid=GA1.2.833861141.1553823366; login_bc=1; device_token=71ff7d55a253e118a673c3e57a2531e8; privacy_policy_agreement=1; c_type=23; a_type=0; b_type=1; module_orders_mypage=%5B%7B%22name%22%3A%22sketch_live%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22tag_follow%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22recommended_illusts%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22everyone_new_illusts%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22following_new_illusts%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22mypixiv_new_illusts%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22spotlight%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22fanbox%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22featured_tags%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22contests%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22user_events%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22sensei_courses%22%2C%22visible%22%3Atrue%7D%2C%7B%22name%22%3A%22booth_follow_items%22%2C%22visible%22%3Atrue%7D%5D; is_sensei_service_user=1; yuid_b=IwmYISU; login_ever=yes; __utmv=235335808.|2=login%20ever=yes=1^3=plan=normal=1^5=gender=male=1^6=user_id=39347803=1^9=p_ab_id=6=1^10=p_ab_id_2=5=1^11=lang=zh=1; PHPSESSID=a3205681379282c5728e90f318cf0467; stacc_mode=unify; __utma=235335808.1000168084.1553823364.1553834834.1553835521.5; __utmz=235335808.1553835521.5.2.utmcsr=baidu|utmccn=(organic)|utmcmd=organic; __utmt=1; ki_t=1553823381979%3B1553823381979%3B1553836399898%3B1%3B23; ki_r=; __utmb=235335808.20.9.1553836399349; tag_view_ranking=BU9SQkS-zU~y8GNntYHsi~o2vM33GyaO~NpsIVvS-GF~RTJMXD26Ak~LJo91uBPz4~R15QRYFK7S~0xsDLqCEW6~MM6RXH_rlN~rsY0-URJyi~gooMLQqB9a~lNKNgeqwXf~5oPIfUbtd6~4HF33EJeed~HcBlC3F1Sy~0Sds1vVNKR~Txs9grkeRc~VbPCYJXdEP~DADQycFGB0~9TPuxVVpm_~faHcYIP1U0~tgP8r-gOe_~pEXFxboc77~BX1TR43HEh~Vgp1Qch3kM~Lt-oEicbBr~rqnJSF7cpq~QQhA-V4ka6~jT6qMyoHEQ~QliAD3l3jr~0L2h0OagIG~UJHUTeB0nE~WjMmxmL00S~QiqS_ELlwC~aCv01L8wRh~QiS8jHBQYX~KTEKeOjm4d~qWFr0Atl5X~vSWEvTeZc6~HBYFbIUAS8~mZurA-1CO-~w8ffkPoJ_S
  thread: 5
  enableProxy: true

hanime:
  home: https://hanime.tv/
  savePath: F:\hanime
  imageApi: https://hanime.tv/api/v3/community_uploads?channel_name__in[]=@{type}&__offset=@{offset}&__order=created_at,DESC
  thread: 24
  videoListApi: https://search.hanime.tv
  videoDownloadApi: https://members.hanime.tv/api/v1/downloads/@{slug}
  auth: ad170b14e4c91572f9ab09709fae0754
  auth_expires: 1557134607
  enableProxy: true

wallhaven:
  home: https://wallhaven.cc
  savePath: G:\wallhaven
  imageApi: https://wallhaven.cc/search?q=&categories=@{categories}&purity=@{purity}&atleast=@{atleast}&sorting=date_added&order=desc&page=@{page}
  categories:
    - general
    - anime
    - people
  purity:
    - SFW
    - sketchy
    - NSFW
  cookie: __cfduid=d7de3bd7c0b7f35648d7ca4b45d092d0a1556795980; _pk_ses.1.01b8=1; remember_web_59ba36addc2b2f9401580f014c7f58ea4e30989d=eyJpdiI6IitTTVRFNFBmZVFtQ0ZZMit0M1JEWlE9PSIsInZhbHVlIjoiQmtqZXNRTlphbTlOMmlhUFJRSDhqaW5RNW9zMGhkWDVFQnd6YzRxYlNDbEM5Sys5bFhadlE1SllSOGZrb281TGFrTkxtaEFLaGtuUkY1azBueXlRS2JtT1k5cWtxVU5tbzJNMmlOOWRIalwvVmM3cE5Pd3BDd0JkSHlneEYrTVhTNWhtUER6Y1FXcmxiMUxcL2hjTk9cL05sSDJJZmJQQzhYRU1uRU5JQjZvQ25NOWRnaHBVeWp6XC9leXBEa3B2aVhpYyIsIm1hYyI6Ijg0ZTg3OTcwYTE4OWRlOWE4MjUyODMyNTIxYjU2NTBmMWM3NWM4Njc0MjE4YTU3M2I5NGE0NTI3YTg5Yzc2MDkifQ%3D%3D; _pk_id.1.01b8=893fa051d6a2880e.1559142259.2.1559144190.1559144132.; XSRF-TOKEN=eyJpdiI6IlFFNm4xNzRUUHB0ZjRTSG56NDlObXc9PSIsInZhbHVlIjoiN0dkSGN1YTdGN3FzM3dLRnJ6UFBrUkpSNXNiOEpTRWVzT3pTTUlTNkpQMXQ2YkNsbjRReFRxdlc1bWNrR0phSSIsIm1hYyI6ImU4MDFmOWNjMjNkMjllYmY2MGQ4MTNiYWFiMDZiNGFmZDE0MWZjMTg0MTUyMjc1YzNiZDM4N2NhMDBjYTMxNmMifQ%3D%3D; wallhaven_session=eyJpdiI6InNXRzZGYzhPRlh0SzQ3Z2hMd0dmWkE9PSIsInZhbHVlIjoiUUlxR3hMNnlmWm5FUlpEQjE4WDFmWXdYTmRjVXhGNGZ5bDM0anRSTUpOWU1pTEtPZkpwcnZVU1ZcL2ZyQnVjTlEiLCJtYWMiOiIzY2Y4MTlhMDQ1MjczMWU3ZGI4Y2E1ZjM2YzIxNTJhY2MwZjZjMzE3MzgxN2ExOTc1OGE1NzcwOWQzNDEzN2Q1In0%3D
  enableProxy: true

longteng:
  home: http://www.longteng12345.com
  rank: http://www.longteng12345.com/top/allvisit/@{page}.html
  savePath: C:\longteng
  thread: 30
  enableProxy: false

javhihi:
  home: https://www1.javhihi.com/
  #home: https://www1.javbuz.com/
  #home: https://xart.letfap.com/
  movie: ${javhihi.home}movie?sort=published&page=@{page}&ajax=1
  savePath: E:\javhihi\
  #savePath: D:\javbuz\
  #savePath: D:\xart.letfap\
  thread: 20
  enableProxy: true

avMovie:
  home: http://av.movie/
  savePath: D:\avMovie\
  uncensored: http://av.movie/c/uncensored/@{page}
  videoUrl: http://av.movie/v/@{code}
  videoListUrl: http://av.movie/c/@{type}/@{page}
  playApi: http://api.av.movie/video/players


pornhub:
  home: https://www.pornhub.com
  savePath: D:\pornhub\
  searchUrl: https://www.pornhub.com/video/search?search=@{key}&hd=1&page=@{page}&p=professional&min_duration=10
  channels: https://pornhub.com/channels/@{channelName}/videos?o=da&page=@{page}
  categories:
    - hentai
  categoriesUrl: https://www.pornhub.com/categories/@{categories}
  categoriesUrlByNum: https://pornhub.com/video?c=@{categories}&hd=1&page=@{page}&min_duration=10&p=professional
  incategories: https://pornhub.com/video/incategories/@{categories}/@{incategories}?p=professional&min_duration=10&hd=1&page=@{page}
  thread: 15
  enableProxy: true

youtube:
  home: https://www.findyoutube.net/
  api: https://www.findyoutube.net/result
  savePath: F:\youtube\
  thread: 5
  enableProxy: true
  googleApi:
    #key: AIzaSyA7H9oVSXwPbOyIaC2kKV1UTtoOyjRjgmw
    key: AIzaSyBSLTrFguRE5p75BJ6OzhwXuiPHTTO8Ryc
    playlists: https://www.googleapis.com/youtube/v3/playlists?part=snippet&channelId=@{channelId}&key=${youtube.googleApi.key}&maxResults=50
    playlistItems: https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=@{playlistId}&key=${youtube.googleApi.key}&maxResults=50
    search: https://www.googleapis.com/youtube/v3/search?key=${youtube.googleApi.key}&part=snippet&channelId=@{channelId}&maxResults=50&type=video

by114:
  home: https://www.by114.pw/
  template: https://www.by114.pw/forum-@{type}-@{page}.html
  savePath: C:\by114\

proxyrarbg:
  home: https://proxyrarbg.org/torrents.php
  template: https://proxyrarbg.org/torrents.php?category=@{category}&page=@{page}
  savePath: C:\proxyrarbg\

javbangers:
  home: https://www.javbangers.com/
  template: https://www.javbangers.com/categories/@{categories}/?mode=async&function=get_block&block_id=list_videos_common_videos_list&sort_by=post_date&from=@{page}&_=@{time}
  savePath: E:\javbangers\
  cookie: _ga=GA1.2.691909481.1600091699; PHPSESSID=6be78946339a08799fcf38140ae7a234; kt_qparams=id%3D102615%26dir%3D127-coco; kt_ips=65.52.182.116; kt_tcookie=1; _gid=GA1.2.1199354712.1600969029; _gat_gtag_UA_154629456_1=1; kt_is_visited=1; kt_member=87beabf211fcb170ea555f40a006fab2
  enableProxy: true
  thread: 30
  filterKey: FC2-PPV,Pacopacomama,Muramura,pacopacomama,FC2,H0930,C0930,H4610,10Musume,Mosaic Removed,台湾色情,Jukujo-club,Taiwan,CreampieInAsia,HeyDouga,Heydouga,XXX-AV,Lesshin,Nyoshin,素人,Kin8tengoku,fc2,fc2-ppv,Fanta Dream,หนังอาร์เกาหลีอัพเดทใหม่ๆ,ガチん娘,Korean,G-Queen,Shemales,amateur,Sol sanchez,Amwf,jukujo-club,TOEN,DASD,HGOT,HND,MIAA,SPRD,T28,Mywife,Thai,KRMV,Gachinco,Vpsds,HOON,SIRO,SR0,GVG,200GANA,300MAAN,ORE-,STAR-,SOD-,unkotare,NSPS-,SDMT-,SVS-,S-Cute,MXSPS,DJE-,BFFF-,BFJG-,DOCP-,PZD-,MDS-,MARA-,mktk,JTP,XVSR,WSP,America,ipx,SL-

kissjav:
  home: https://kissjav.com
  savePath: C:\kissjav\
  template: https://kissjav.com/videos/@{category}/@{page}/
  cookie: Angie_89d7248ae8=2c1ac182980f365658895889643d44a4
  thread: 30
  enableProxy: true

javbus:
  home: https://www.javbus.com
  enableProxy: true
  thread: 10
  actressesListTemplate: ${javbus.home}/@{category}/actresses/@{page}
  actressesDetailsTemplate: ${javbus.home}/@{category}/star/@{name}
  avTemplate: ${javbus.home}/@{code}
  magnetApi: https://www.javbus.com/ajax/uncledatoolsbyajax.php?gid=@{gid}&lang=zh&uc=1
  savePath: E:\javbus\

javrave:
  home: https://javrave.club/
  template: https://javrave.club/cat/@{category}/page/@{page}/
  savePath: E:\javrave\
  enableProxy: true
  thread: 30
  api: https://javideo.pw/api/source/@{key}
  filterKey: FC2-PPV,Pacopacomama,Muramura,pacopacomama,FC2,H0930,C0930,H4610,10Musume,Mosaic Removed,台湾色情,Jukujo-club

javfull:
  home: https://javfull.net/
  template: https://javfull.net/@{category}/page/@{page}/
  savePath: C:\javfull\
  enableProxy: true
  thread: 30
  api: https://feurl.com/api/source/@{key}
  filterKey: FC2-PPV,Pacopacomama,Muramura,pacopacomama,FC2,H0930,C0930,H4610,10Musume,Mosaic Removed,台湾色情

proxy:
  enabled: false
  socks:
    #host: 192.168.31.184
    host: 127.0.0.1
    port: 1080
  http:
    #host: 192.168.31.184
    host: 127.0.0.1
    port: 10809

FFmpegPath: C:\\ffmpeg\\bin\\

spring:
  application:
    name: video-spider
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/file
  redis:
    host: 127.0.0.1
    port: 6379
