eporner:
   home: https://www.eporner.com
   savePath: C:\eporner\
   category:
      UHD: https://www.eporner.com/category/4k-porn/
   thread: 40  
   
javfinder:
   home: https://www3.javfinder.is
   savePath: C:\javfinder 
   category:
      Uncensored: https://www3.javfinder.is/category/uncensored/page-@{page}.html
   categoryTemplate: https://www3.javfinder.is/category/@{category}/page-@{page}.html 
   thread: 30
      
proxy:
   host: 127.0.0.1
   port: 1080     
   
spring:
   data:
      mongodb:
         uri: mongodb://127.0.0.1:27017/file